services:

  # Comment this service out if you have PostgreSQL up and running already.
  # In that case, you should also change the config.yaml file.
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  migrator:
    build:
      context: .
      dockerfile: ./cmd/migrator/Dockerfile
    environment:
      - CONFIG_PATH=${MIGRATION_CONFIG_PATH}
      - OPERATION=${OPERATION}
    depends_on:
      - postgres

  app:
    build: .
    environment:
      - CONFIG_PATH=${CONFIG_PATH}
    ports:
      - "42042:42042"
    depends_on:
      - migrator
      - postgres

volumes:
  pgdata: