env: "local" # local, dev, prod
token_ttl: 1h
postgres:
    host: "postgres"
    port: 5432
    user: "postgres"
    password: "password"
    dbname: "sso"
    sslmode: "disable"

grpc:
    port: 42042
    timeout: 5s

privateKeyPath: /path/to/private_key_ed25519.pem
publicKeyPath: /path/to/public_key_ed25519.pem